import "./globals.css";
import Image from 'next/image'
import ticket from '../public/ticket.svg'
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <nav className="nav">
          <div className="logo">
            <Image
              src={ticket}
              width={75}
              height={75}
              alt="Picture of the author"
            />
            <h1 className="heroTitle">Task</h1> 
            <h1 className="heroTitle" style={{color:"#a45fbe"}}>Master</h1>
          </div>
          <div style={{
            display:"flex",
            gap:"20px"
          }}>
            <Link href={"/"}><h1 className="heroTitle">Dashboard</h1></Link>
            <Link href={"/tickets"}> <h1 className="heroTitle">Tickets</h1></Link>
          </div>

          </nav>
          {children}
        </body>
    </html>
  );
}
