import "./globals.css";
import Navbar from "./navbar"
import { CartProvider } from './cartContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <CartProvider>
            <Navbar></Navbar>
            {children}
          </CartProvider>

        </body>
    </html>
  );
}
